<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.4.12 setup script
 * Date: Wed, 22 Jul 2015 15:57:32 +0200
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '2web SQL server';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '/var/run/mysqld/mysqld.sock';
#$cfg['Servers'][$i]['ssl'] = true;
#$cfg['Servers'][$i]['ssl_ca'] = '/etc/ssl/ca/signing-ca.pem';
$cfg['Servers'][$i]['connect_type'] = 'socket';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['AllowRoot'] = true;

/* End of servers configuration */

$cfg['UploadDir'] = '/tmp';
$cfg['SaveDir'] = '';
$cfg['ForceSSL'] = false;
$cfg['blowfish_secret'] = '55afa138ca9a87.01481849';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['ShowSQL'] = true;
?>