-- MySQL Script generated by MySQL Workbench
-- Tue Feb 28 22:42:31 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hosting
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hosting` ;

-- -----------------------------------------------------
-- Schema hosting
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hosting` DEFAULT CHARACTER SET utf8 ;
USE `hosting` ;

-- -----------------------------------------------------
-- Table `hosting`.`pdns_cryptokeys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hosting`.`pdns_cryptokeys` ;

CREATE TABLE IF NOT EXISTS `hosting`.`pdns_cryptokeys` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `domain_id` INT NOT NULL,
  `flags` INT NOT NULL,
  `active` TINYINT NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `domainidindex` (`domain_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hosting`.`pdns_domainmetadata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hosting`.`pdns_domainmetadata` ;

CREATE TABLE IF NOT EXISTS `hosting`.`pdns_domainmetadata` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `domain_id` INT NOT NULL,
  `kind` VARCHAR(32) NOT NULL,
  `content` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `domainmeta_idx` (`domain_id` ASC, `kind` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hosting`.`contact_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hosting`.`contact_data` ;

CREATE TABLE IF NOT EXISTS `hosting`.`contact_data` (
  `contact_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Contact ID as integer',
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date of creation',
  `updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Last update of the account',
  `remember_token` varchar(255) DEFAULT NULL COMMENT 'Used by the framework to help against Remember Me cookie hijacking. The value is refreshed upon login and logout. If a cookie is hijacked by a malicious person, logging out makes the hijacked cookie useless since it doesn''t match anymore.',
  `username` VARCHAR(128) NOT NULL COMMENT 'Regular username',
  `password` VARCHAR(255) NOT NULL COMMENT 'Cleartext password',
  `salt` VARCHAR(32) NULL COMMENT 'Salt for stuff',
  `firstname` VARCHAR(32) NOT NULL COMMENT 'Users firstname',
  `lastname` VARCHAR(32) NOT NULL COMMENT 'Users lastname',
  `organization` VARCHAR(64) NULL DEFAULT NULL COMMENT 'Organization name',
  `orgnr` VARCHAR(16) NULL DEFAULT NULL COMMENT 'Organization or social security number',
  `userType` ENUM('0', '1') NULL DEFAULT NULL COMMENT '0 = person, 1 = organisation',
  `address1` VARCHAR(64) NOT NULL COMMENT 'Street and number',
  `address2` VARCHAR(64) NULL DEFAULT NULL COMMENT 'C/O if any',
  `city` VARCHAR(64) NOT NULL COMMENT 'Name of users city',
  `zip` VARCHAR(8) NULL DEFAULT NULL COMMENT 'Zipcode',
  `country` VARCHAR(64) NOT NULL COMMENT 'Users country',
  `phone` VARCHAR(16) NULL DEFAULT NULL COMMENT 'User phonenumber in international format.',
  `fax` VARCHAR(16) NULL COMMENT 'Users faxnumber if any',
  `email` VARCHAR(255) NOT NULL COMMENT 'Users alternative email adress',
  UNIQUE INDEX `email` (`email` ASC),
  PRIMARY KEY (`contact_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1100
CHECKSUM = 1
DEFAULT CHARACTER SET = utf8;

--
-- Tabellstruktur `password_resets`
--
DROP TABLE IF EXISTS `hosting`.`password_resets` ;

CREATE TABLE `password_resets` (
  `email` varchar(255) NOT NULL,
  `token` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `hosting`.`domain_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hosting`.`domain_data` ;

CREATE TABLE IF NOT EXISTS `hosting`.`domain_data` (
  `domain_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Integer value of domain. Used as GID (group ID).',
  `domain_name` VARCHAR(255) NOT NULL COMMENT 'Registered TLD',
  `registered_date` DATE NOT NULL COMMENT 'Registration date of TLD',
  `expiration_date` DATE NOT NULL COMMENT 'Expiration date of TLD',
  `agent_contact` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'Agent contact ID as integer. Foregin key constraint in table contact_data via domain_contacts.',
  `owner_contact` INT(10) UNSIGNED NOT NULL COMMENT 'Owner contact ID as integer. Foregin key constraint in table contact_data via domain_contacts.',
  `admin_contact` INT(10) UNSIGNED NOT NULL COMMENT 'Admin contact ID as integer. Foregin key constraint in table contact_data via domain_contacts.',
  `tech_contact` INT(10) UNSIGNED NOT NULL COMMENT 'Technical contact ID as integer. Foregin key constraint in table contact_data via domain_contacts.',
  `billing_contact` INT(10) UNSIGNED NOT NULL COMMENT 'Billing contact ID as integer. Foregin key constraint in table contact_data via domain_contacts.',
  PRIMARY KEY (`domain_id`),
  INDEX `Agent_contact_01_idx` (`agent_contact` ASC),
  INDEX `Owner_contact_01_idx` (`owner_contact` ASC),
  INDEX `Admin_contact_01_idx` (`admin_contact` ASC),
  INDEX `Tech_contact_01_idx` (`tech_contact` ASC),
  INDEX `Billing_contact_01_idx` (`billing_contact` ASC),
  UNIQUE INDEX `domain_name_UNIQUE` (`domain_name` ASC),
  CONSTRAINT `Agent_contact_01`
    FOREIGN KEY (`agent_contact`)
    REFERENCES `hosting`.`contact_data` (`contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Owner_contact_01`
    FOREIGN KEY (`owner_contact`)
    REFERENCES `hosting`.`contact_data` (`contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Admin_contact_01`
    FOREIGN KEY (`admin_contact`)
    REFERENCES `hosting`.`contact_data` (`contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Tech_contact_01`
    FOREIGN KEY (`tech_contact`)
    REFERENCES `hosting`.`contact_data` (`contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Billing_contact_01`
    FOREIGN KEY (`billing_contact`)
    REFERENCES `hosting`.`contact_data` (`contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1100
CHECKSUM = 1
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `hosting`.`pdns_domains_old`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hosting`.`pdns_domains_old` ;

CREATE TABLE IF NOT EXISTS `hosting`.`pdns_domains_old` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `master` VARCHAR(128) NULL DEFAULT NULL,
  `last_check` INT(11) NULL DEFAULT NULL,
  `type` VARCHAR(6) NOT NULL,
  `notified_serial` INT(11) NULL DEFAULT NULL,
  `account` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_index` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hosting`.`pdns_records`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hosting`.`pdns_records` ;

CREATE TABLE IF NOT EXISTS `hosting`.`pdns_records` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `domain_id` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `type` VARCHAR(10) NULL DEFAULT NULL,
  `content` MEDIUMTEXT NULL DEFAULT NULL,
  `ttl` INT(11) NULL DEFAULT NULL,
  `prio` INT(11) NULL DEFAULT NULL,
  `change_date` INT(11) NULL DEFAULT NULL,
  `disabled` TINYINT(1) NULL DEFAULT 0,
  `ordername` VARCHAR(255) BINARY NULL DEFAULT NULL,
  `auth` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `nametype_index` (`name` ASC, `type` ASC),
  INDEX `domain_id` (`domain_id` ASC),
  INDEX `recordorder` (`domain_id` ASC, `ordername` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hosting`.`pdns_tsigkeys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hosting`.`pdns_tsigkeys` ;

CREATE TABLE IF NOT EXISTS `hosting`.`pdns_tsigkeys` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `algorithm` VARCHAR(50) NULL DEFAULT NULL,
  `secret` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `namealgoindex` (`name` ASC, `algorithm` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hosting`.`pdns_supermasters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hosting`.`pdns_supermasters` ;

CREATE TABLE IF NOT EXISTS `hosting`.`pdns_supermasters` (
  `ip` VARCHAR(64) NOT NULL,
  `nameserver` VARCHAR(255) NOT NULL,
  `account` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`ip`, `nameserver`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hosting`.`pdns_comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hosting`.`pdns_comments` ;

CREATE TABLE IF NOT EXISTS `hosting`.`pdns_comments` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `domain_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `type` VARCHAR(10) NOT NULL,
  `modified_at` INT NOT NULL,
  `account` VARCHAR(40) NOT NULL,
  `comment` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `comments_domain_id_idx` (`domain_id` ASC),
  INDEX `comments_name_type_idx` (`name` ASC),
  INDEX `comments_order_idx` (`domain_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hosting`.`nameserver_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hosting`.`nameserver_data` ;

CREATE TABLE IF NOT EXISTS `hosting`.`nameserver_data` (
  `nameserver` VARCHAR(255) NOT NULL COMMENT 'Registered name of nameserver',
  `ip` VARCHAR(128) NOT NULL COMMENT 'IP adress. Can be IPv4 or IPv6',
  PRIMARY KEY (`nameserver`, `ip`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hosting`.`domain_nameserver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hosting`.`domain_nameserver` ;

CREATE TABLE IF NOT EXISTS `hosting`.`domain_nameserver` (
  `domain_data_id` INT(10) UNSIGNED NOT NULL COMMENT 'Domain ID as integer. Foregin key constraint in table domain_data.',
  `nameserver` VARCHAR(255) NOT NULL COMMENT 'Registeres nameserver. Foregin key constraint in table nameserver_data.',
  INDEX `Nameserver_1_idx` (`nameserver` ASC),
  INDEX `Domain_01_idx` (`domain_data_id` ASC),
  CONSTRAINT `domain_nameserver_nameserver_1`
    FOREIGN KEY (`nameserver`)
    REFERENCES `hosting`.`nameserver_data` (`nameserver`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `domain_nameserver_domain_01`
    FOREIGN KEY (`domain_data_id`)
    REFERENCES `hosting`.`domain_data` (`domain_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hosting`.`domain_contacts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hosting`.`domain_contacts` ;

CREATE TABLE IF NOT EXISTS `hosting`.`domain_contacts` (
  `domain_data_id` INT(10) UNSIGNED NOT NULL COMMENT 'Domain ID as integer. Foregin key constraint in table domain_data.',
  `contact_data_id` INT(10) UNSIGNED NOT NULL COMMENT 'Contact ID as integer. Foregin key constraint in table contact_data.')
ENGINE = InnoDB
AUTO_INCREMENT = 1100;

USE `hosting` ;

-- -----------------------------------------------------
-- Placeholder table for view `hosting`.`ftpuser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hosting`.`ftpuser` (`username` INT, `groupname` INT, `passwd` INT, `salt` INT, `uid` INT, `gid` INT, `homedir` INT, `shell` INT);

-- -----------------------------------------------------
-- Placeholder table for view `hosting`.`mailuser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hosting`.`mailuser` (`home` INT, `username` INT, `groupname` INT, `uid` INT, `gid` INT, `password` INT, `salt` INT);

-- -----------------------------------------------------
-- Placeholder table for view `hosting`.`pdns_domains`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hosting`.`pdns_domains` (`id` INT, `name` INT, `master` INT, `last_check` INT, `type` INT, `notified_serial` INT, `account` INT);

-- -----------------------------------------------------
-- View `hosting`.`ftpuser`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `hosting`.`ftpuser` ;
DROP TABLE IF EXISTS `hosting`.`ftpuser`;
USE `hosting`;
CREATE  OR REPLACE VIEW `ftpuser` AS SELECT contact_data.username AS username, domain_data.domain_name AS groupname, contact_data.password AS passwd, contact_data.salt AS salt, contact_data.contact_id AS uid, domain_data.domain_id AS gid, CONCAT('/home/hosting/',domain_data.domain_name,'/htdocs/') AS homedir, NULL AS shell FROM contact_data JOIN domain_contacts ON domain_contacts.contact_data_id = contact_data.contact_id JOIN domain_data ON domain_data.domain_id = domain_contacts.domain_data_id;

-- -----------------------------------------------------
-- View `hosting`.`mailuser`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `hosting`.`mailuser` ;
DROP TABLE IF EXISTS `hosting`.`mailuser`;
USE `hosting`;
CREATE  OR REPLACE VIEW `mailuser` AS SELECT CONCAT('/home/hosting/',domain_data.domain_name) AS home, contact_data.username AS username, domain_data.domain_name AS groupname, contact_data.contact_id AS uid, domain_data.domain_id AS gid, contact_data.password AS password, contact_data.salt AS salt FROM contact_data JOIN domain_contacts ON domain_contacts.contact_data_id = contact_data.contact_id JOIN domain_data ON domain_data.domain_id = domain_contacts.domain_data_id;

-- -----------------------------------------------------
-- View `hosting`.`pdns_domains`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `hosting`.`pdns_domains` ;
DROP TABLE IF EXISTS `hosting`.`pdns_domains`;
USE `hosting`;
CREATE  OR REPLACE VIEW `pdns_domains` AS SELECT domain_id AS id, domain_name AS name, NULL AS master, NULL AS last_check, 'NATIVE' AS type, DATE_FORMAT(DATE(NOW()), '%Y%m%d%H') AS notified_serial, NULL AS account FROM domain_data;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
